color: orange
fieldLayouts:
  1ab8378a-5c3d-4bed-b850-949e287520bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-14T12:03:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0722ce1e-e56c-4aab-ba89-5a2c29c4f361
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-14T12:09:51+00:00'
            elementCondition: null
            fieldUid: 8c0b9121-2d47-4e0b-99d6-16250224f4ab # About Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 640c45be-f0d3-48ae-98cd-2cb2c25a8554
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-14T12:09:51+00:00'
            elementCondition: null
            fieldUid: bc3a72f1-c7c7-42f7-adc5-cf28d9b70a11 # About Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7489183-79de-417d-afe7-ee1a7e7c831f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aa197335-ba68-42fd-9222-6006da74c6a4
        userCondition: null
handle: home
hasTitleField: true
icon: ''
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
