defaultPlacement: end
fieldLayouts:
  ff2b4792-2824-4f9f-a76a-6d293cc74bcc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T11:14:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 4ba9fcee-eaa1-4cc3-94dd-231144b30d93
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b219148c-8c53-4f55-9d12-3ad00a5bb23d
        userCondition: null
handle: priceRanges
name: 'Price Ranges'
siteSettings:
  831239cc-896f-4292-8653-de842081d524: # Funbags
    hasUrls: true
    template: home.twig
    uriFormat: 'price-ranges/{slug}'
structure:
  maxLevels: 1
  uid: da4fac7f-6e46-454b-a938-e7606d4473f4
